import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { lastRatingDateMem } from './utils'
import { lastRatingDate } from './db'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const lastContribution = await lastRatingDate();
  const lastContributionDateStr = lastContribution.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <html lang="en">
      <body className="h-screen bg-white">
        <header className="flex justify-center items-start h-8 mb-8 border-b-slate-100 border-2 ">
          <h1 className="text-lg">Community Notes Data Explorer</h1>
        </header>
        <main>
        {children}
        </main>
        <footer className="text-xs text-center mt-8">
          <a href='https://twitter.com/i/communitynotes/download-data'>Data</a> includes contributions up until {lastContributionDateStr}.
        </footer>
      </body>
    </html>
  )
}
